[project]
name = "travel-solution"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "azure-identity>=1.25.1",
    "fastapi>=0.115.5",
    "uvicorn[standard]>=0.32.1",
    "jinja2>=3.1.4",
]
